### ISSUE TITLE
can't modify frozen String on ruby 2.3.0

### ISSUE THREAD

**Issue by masterkain** [rails/rails-dom-testing#48]
On Ruby 2.3.0, when putting the directive `# frozen_string_literal: true` on top of the spec file, this happens:

```
     Failure/Error: assert_select '[content=?]', 'meta,description'
     RuntimeError:
       can't modify frozen String
     # /Users/kain/.rvm/gems/ruby-2.3.0/gems/rails-dom-testing-1.0.7/lib/rails/dom/testing/assertions/selector_assertions/substitution_context.rb:8:in `sub!'
     # /Users/kain/.rvm/gems/ruby-2.3.0/gems/rails-dom-testing-1.0.7/lib/rails/dom/testing/assertions/selector_assertions/substitution_context.rb:8:in `substitute!'
     # /Users/kain/.rvm/gems/ruby-2.3.0/gems/rails-dom-testing-1.0.7/lib/rails/dom/testing/assertions/selector_assertions/html_selector.rb:77:in `extract_selector'
     # /Users/kain/.rvm/gems/ruby-2.3.0/gems/rails-dom-testing-1.0.7/lib/rails/dom/testing/assertions/selector_assertions/html_selector.rb:10:in `initialize'
     # /Users/kain/.rvm/gems/ruby-2.3.0/gems/rails-dom-testing-1.0.7/lib/rails/dom/testing/assertions/selector_assertions.rb:167:in `new'
     # /Users/kain/.rvm/gems/ruby-2.3.0/gems/rails-dom-testing-1.0.7/lib/rails/dom/testing/assertions/selector_assertions.rb:167:in `assert_select'
     # ./spec/controllers/products_controller_spec.rb:247:in `block (5 levels) in <top (required)>'
```

**Comment by prathamesh-sonpatki** [comment]
@masterkain Can you check if it's happening on master? I think https://github.com/rails/rails-dom-testing/blob/f94ac0a394bd4cc1f03661005d69b0d69453fbf2/lib/rails/dom/testing/assertions/selector_assertions/substitution_context.rb#L7 should have fixed it.

**Comment by masterkain** [comment]
yeah it looks good, waiting on release, thanks

**Comment by donv** [comment]
Hi!  Could this fix be backported to a 1.x release?  Rails < 5 cannot use the 2.x releases.

**Comment by donv** [comment]
Workaround for rails-dom-testing 1.x:

```ruby
class SubstitutionContext
  def substitute_with_dup!(selector, *args)
    substitute_without_dup!(selector.dup, *args)
  end
  alias_method_chain :substitute!, :dup
end
```

Good enough for me.

**Comment by kaspth** [comment]
Sure, open a pull request. I'll be happy have the original fix backported, thanks 😄

**Comment by donv** [comment]
Thanks for the response, @kaspth , but with the workaround, or just not use the substitution feature, I am good without the fix 😄  .

**Comment by kaspth** [comment]
Alright, then 👍
